### ISSUE TITLE
Min max and mean in diversity analysis exercise didn't work

### ISSUE THREAD

**Issue by AbrahamAvelar** [carpentries-lab/metagenomics-analysis#10]
In this episode nothing is learned when the min, max and mean lines are ran. It is not clear their purpose.

https://carpentries-incubator.github.io/metagenomics/09-diversity-analysis/index.html

---

**Comment by Bedxxe** [comment]
I agree, at the moment that is used in the lesson, it does not give useful information. I think that the command line:
$ sample_sums(merged_metagenomes)
$  JC1A   JP4D 
   2815 102444 
Could be used in posterior instances in the lesson in order to show the difference of reads that each of the libraries has and how this highlights the urgency for normalization before a scrutinous analysis of the data. If we agree, we can include a little segment for normalization in the lesson

**Comment by Bedxxe** [comment]
I have added the "summary()" command in one line of code in order to obtain the desired statistic content of the libraries
