### ISSUE TITLE
Improve Trimming and Filtering episode

### ISSUE THREAD

**Issue by Czirion** [carpentries-lab/metagenomics-analysis#58]
**Reviewer's comments**: 
1) In the [Trimming and Filtering](https://carpentries-incubator.github.io/metagenomics/03-trimming-filtering/index.html) episode, it may be useful to provide the Trimmomatic adapter file (cp ~/.miniconda3/pkgs/trimmomatic-0.38-0/share/trimmomatic-0.38-0/adapters/TruSeq3-PE.fa .) as a downloadable option from the material, in case the command doesn't work due to different versions.  
2) Idea: on the [Trimming and Filtering](https://carpentries-incubator.github.io/metagenomics/03-trimming-filtering/index.html) section, give an example of how a multi-line command would look like.  
3) Maybe mention something about anaconda/minicionda, as it appears in some commands. There is a box about conda but the relationship between them is not clear. **To do**: Check in which episodes is mentioned and choose a place for this.

**Comment by nselem** [comment]
1 This issue duplicates issue #66 and issue #59 
2 A box has been added on the [Trimming and Filtering](https://carpentries-incubator.github.io/metagenomics/03-trimming-filtering/index.html) episode with an echo hello world example of the multiline command. 
3. The following lines have been added to the [Setup](https://carpentries-incubator.github.io/metagenomics-workshop/setup.html) page:
"To make a [Conda](https://conda.io/projects/conda/en/latest/index.html) environment, first you need to install Conda; we recommend installing the [Miniconda3](https://docs.conda.io/en/latest/miniconda.html) version. Miniconda is a package manager that includes Conda and its dependencies and simplifies the installation process. Please first install Miniconda3 (installation instructions below), and then proceed to the installation of the environment."

We also introduce conda in the [Assessing read quality episode](https://carpentries-incubator.github.io/metagenomics/02-assessing-read-quality/index.html), where we use fastqc. This is the right place since fastqc is the first bioinformatic tool used, and now the conda metagenomics environment includes all programs of this lesson.
 The introduction is the following:
"Environments are part of a bioinformatic tendency to do reproducible research, they are a way to share and maintain our programs in their needed versions used for a pipeline with our colleagues and with our future self. FastQC is not activated in the (base) environment but this AWS instances came with an environment called metagenomics. We need to activate 
it in order to start using FastQC. We will use [Conda](https://docs.conda.io/en/latest/) as our environment manager. Conda is an open source package and environment management system that runs on Windows, macOS and Linux. Conda environments are activated with the `conda activate` direction:  "
